server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 43.138.130.26:80
    gateway:
      routes:
        - id: web-service
          uri: lb://webservice
          predicates:
            - Path=/web/**
        - id: user-service
          uri: lb://userservice
          predicates:
            - Path=/user/**
      default-filters:
        - AddResponseHeader=laoba,6
